redegg/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from redegg.views import (
    AnnualLeaderboard,
    ContestLeaderboard,
    ContestListView,
    PredictionDetailView,
    PredictionListView,
    create_prediction,
    home,
    rules,
)

urlpatterns = [
    path("", home, name="home"),
    path("rules/", rules, name="rules"),
    path("contests/", ContestListView.as_view(), name="contest_list"),
    path(
        "contest/<slug:contest_slug>/",
        create_prediction,
        name="create_prediction",
    ),
    path(
        "contest/<slug:contest_slug>/leaderboard/",
        ContestLeaderboard.as_view(),
        name="contest_leaderboard",
    ),
    path("predictions/", PredictionListView.as_view(), name="prediction_list"),
    path(
        "prediction/<str:prediction_id>/",
        PredictionDetailView.as_view(),
        name="prediction_detail",
    ),
    path(
        "leaderboard/<int:year>/",
        AnnualLeaderboard.as_view(),
        name="global_leaderboard",
    ),
]

ufcapi/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from ufcapi import settings
from ufcscraper.filters import FightFilter
from ufcscraper.models import Event, Fighter, Fight
from django.urls import path, include

from rest_framework import routers, serializers, viewsets, filters
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework_api_key.permissions import HasAPIKey
from django_filters.rest_framework import DjangoFilterBackend


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ["url", "username", "email", "is_staff"]


class EventSerializer(serializers.HyperlinkedModelSerializer):
    details = serializers.HyperlinkedIdentityField(view_name="event-detail")

    class Meta:
        model = Event
        fields = [
            "id",
            "details",
            "location",
            "date",
            "upcoming",
            "link",
            "event_id",
            "name",
            "type",
            "completed",
        ]


class FighterSerializer(serializers.HyperlinkedModelSerializer):
    details = serializers.HyperlinkedIdentityField(view_name="fighter-detail")

    class Meta:
        model = Fighter
        fields = [
            "id",
            "details",
            "link",
            "fighter_id",
            "photo_url",
            "first_name",
            "last_name",
            "nickname",
            "height",
            "weight",
            "reach",
            "stance",
            "belt",
            "win",
            "loss",
            "draw",
        ]


class FightSerializer(serializers.HyperlinkedModelSerializer):
    details = serializers.HyperlinkedIdentityField(view_name="fight-detail")
    fighter_one = serializers.PrimaryKeyRelatedField(queryset=Fighter.objects.all())
    fighter_two = serializers.PrimaryKeyRelatedField(queryset=Fighter.objects.all())
    winner = serializers.PrimaryKeyRelatedField(
        queryset=Fighter.objects.all(), allow_null=True
    )
    fighter_one_detail = FighterSerializer(source="fighter_one", read_only=True)
    fighter_two_detail = FighterSerializer(source="fighter_two", read_only=True)

    class Meta:
        model = Fight
        fields = [
            "id",
            "details",
            "fight_id",
            "position",
            "weight_class",
            "fighter_one",
            "fighter_two",
            "fighter_one_detail",
            "fighter_two_detail",
            "method",
            "round",
            "time",
            "event",
            "belt",
            "bonus",
            "wl_fighter_one",
            "wl_fighter_two",
            "winner",
        ]


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all().order_by("-date")
    serializer_class = EventSerializer
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["upcoming", "completed", "type", "event_id"]
    search_fields = ["name", "location"]
    permission_classes = [HasAPIKey | IsAuthenticatedOrReadOnly]


class FighterViewSet(viewsets.ModelViewSet):
    queryset = Fighter.objects.all()
    serializer_class = FighterSerializer
    filter_backends = [DjangoFilterBackend, filters.SearchFilter]
    filterset_fields = ["weight", "stance", "belt", "fighter_id"]
    search_fields = ["first_name", "last_name", "nickname", "fighter_id"]
    permission_classes = [HasAPIKey | IsAuthenticatedOrReadOnly]


class FightViewSet(viewsets.ModelViewSet):
    queryset = Fight.objects.all()
    ordering = [
        "event__date",
        "position",
    ]
    ordering_fields = [
        "event__date",
        "position",
    ]
    serializer_class = FightSerializer
    filterset_class = FightFilter
    filter_backends = [DjangoFilterBackend, filters.OrderingFilter]
    permission_classes = [HasAPIKey | IsAuthenticatedOrReadOnly]


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r"events", EventViewSet)
router.register(r"fighters", FighterViewSet)
router.register(r"fights", FightViewSet)

urlpatterns = [
    path("hq/", admin.site.urls),
    path("accounts/", include("redegg.auth_urls")),
    path("", include("redegg.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
        path("__reload__/", include("django_browser_reload.urls")),
    ] + urlpatterns

redegg/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from ufcscraper.models import Event


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    avatar_url = models.URLField(blank=True, null=True)
    base_username = models.CharField(max_length=50, blank=True, null=True)
    display_username = models.CharField(max_length=50, blank=True, null=True)
    extra_data = models.JSONField(blank=True, null=True)

    def __str__(self):
        return f"{self.display_username} - {self.user.username}"


class Contest(models.Model):
    STATUS_CHOICES = [
        ("open", "Open"),
        ("live", "Live"),
        ("closed", "Closed"),
    ]
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default="open")
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.event.name)
        super().save(*args, **kwargs)

    def calculate_all_predictions_scores(self):
        """
        Calculate the scores for all predictions in the contest.
        Operation is commited and will save the prognostics and predictions after calculation.
        """
        predictions = self.prediction_set.all()
        for prediction in predictions:
            prognostics = prediction.prognostic_set.all()
            for prognostic in prediction.prognostic_set.all():
                prognostic.calculate_points_and_bonus_percentage()
            Prognostic.objects.bulk_update(
                prognostics,
                [
                    "points",
                    "bonus_percentage",
                    "fight_result_won",
                    "method_won",
                    "bonus_won",
                ],
            )
            prediction.calculate_score()
        Prediction.objects.bulk_update(predictions, ["score"])

    def calculate_all_predictions_rank(self):
        """
        Calculate the rank for the predictions of a contest.
        """
        predictions = Prediction.objects.filter(contest_id=self.id).order_by("-score")
        for rank, prediction in enumerate(predictions, start=1):
            prediction.rank = rank
        Prediction.objects.bulk_update(predictions, ["rank"])

    def __str__(self):
        return f"{self.event.name} ({self.status})"


class Prediction(models.Model):
    # Unique anon identifier
    prediction_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contest = models.ForeignKey(Contest, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)  # Raw points
    bonus_modifier = models.IntegerField(default=0)  # Bonus modifier (in percentage)
    score = models.IntegerField(
        default=0
    )  # Total score after points and bonus modifier
    rank = models.IntegerField(default=0)  # Rank in the contest

    def calculate_points(self):
        """
        Calculate the points for the prediction.
        """
        prognostics = self.prognostic_set.all()
        points = 0
        for prognostic in prognostics:
            points += prognostic.points
        self.points = points

    def calculate_bonus_modifier(self):
        """
        Calculate the bonus modifier for the prediction.
        """
        prognostics = self.prognostic_set.all()
        bonus_modifier = 0
        prognostics_won = 0
        for prognostic in prognostics:
            bonus_modifier += prognostic.bonus_percentage
            if prognostic.fight_result_won:
                prognostics_won += 1
        if prognostics_won > 1:
            bonus_modifier += 10 * (prognostics_won - 1)
        self.bonus_modifier = bonus_modifier if bonus_modifier > 0 else 0

    def calculate_score(self):
        """
        Calculate the score for the prediction.
        """
        self.calculate_points()
        self.points = self.points if self.points > 0 else 0
        self.calculate_bonus_modifier()
        self.score = self.points + int(self.points * self.bonus_modifier / 100)

    class Meta:
        unique_together = (
            "user",
            "contest",
        )  # Ensures one prediction per user per contest

    def save(self, *args, **kwargs):
        if not self.prediction_id:
            self.prediction_id = uuid.uuid4()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username} - {self.contest}"


class Prognostic(models.Model):
    METHOD_CHOICES = [
        ("decision", "Decision"),
        ("ko_tko", "KO/TKO"),
        ("submission", "Submission"),
        ("cnc", "CNC"),
    ]

    BONUS_CHOICES = [
        ("fight", "Fight of the Night"),
        ("perf", "Performance of the Night"),
        ("ko", "KO of the Night"),
        ("sub", "Submission of the Night"),
    ]

    prediction = models.ForeignKey(Prediction, on_delete=models.CASCADE)
    fight = models.ForeignKey("ufcscraper.Fight", on_delete=models.CASCADE)
    fight_result = models.ForeignKey(
        "ufcscraper.Fighter", on_delete=models.SET_NULL, null=True, blank=True
    )
    is_draw = models.BooleanField(default=False)
    method = models.CharField(
        max_length=10, choices=METHOD_CHOICES, blank=True, null=True
    )
    bonus = models.CharField(
        max_length=20, choices=BONUS_CHOICES, blank=True, null=True
    )
    points = models.IntegerField(default=0)
    fight_result_won = models.BooleanField(default=False)
    bonus_percentage = models.IntegerField(default=0)
    method_won = models.BooleanField(default=False)
    bonus_won = models.BooleanField(default=False)

    def calculate_points(self):
        """
        Calculate the points and bonus percentage for the prognostic.
        """
        fight = self.fight
        fight_points = 0
        points = 0
        if fight.is_main_event():
            fight_points = 100
        elif fight.is_co_main_event():
            fight_points = 50
        elif fight.is_main_card():
            fight_points = 20
        else:
            fight_points = 10
        if self.fight_result and self.fight_result == fight.winner:
            self.fight_result_won = True
            points = fight_points
        elif not self.fight_result and (self.is_draw and fight.is_draw_or_no_contest()):
            self.fight_result_won = True
            points = fight_points
        else:
            self.fight_result_won = False
            if fight.is_prelim():
                points = -10
        self.points = points

    def calculate_bonus_percentage(self):
        """
        Calculate the bonus percentage for the prognostic.
        """
        bonus_percentage = 0
        if self.method and self.method == self.fight.method_code():
            self.method_won = True
            bonus_percentage += 30
        elif self.method:
            self.method_won = False
            bonus_percentage -= 30
        if self.bonus and self.bonus == self.fight.bonus:
            self.bonus_won = True
            bonus_percentage += 50
        elif self.bonus:
            self.bonus_won = False
            bonus_percentage -= 50
        self.bonus_percentage = bonus_percentage

    def calculate_points_and_bonus_percentage(self):
        """
        Calculate the points and bonus percentage for the prognostic.
        """
        self.calculate_points()
        self.calculate_bonus_percentage()

    def save(self, *args, **kwargs):
        if self.is_draw:
            self.fight_result = None
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.prediction.user.username} - {self.fight} - {self.prediction.contest}"


class GlobalLeaderboard(models.Model):
    year = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    total_score = models.IntegerField()
    rank = models.IntegerField()

    class Meta:
        managed = False
        db_table = "redegg_global_leaderboard"

redegg/forms.py
from django import forms
from django.forms import formset_factory

from ufcscraper.models import Fight, Fighter
from redegg.models import Prognostic


class SocialAccountForm(forms.Form):
    PROVIDERS = (
        ("twitter_oauth2", "Twitter"),
        ("reddit", "Reddit"),
        # Add more providers as needed
    )


class AriaLabelRadioSelect(forms.RadioSelect):
    def create_option(
        self, name, value, label, selected, index, subindex=None, attrs=None
    ):
        option_dict = super().create_option(
            name, value, label, selected, index, subindex=subindex, attrs=attrs
        )
        option_dict["attrs"]["aria-label"] = label
        return option_dict


class PrognosticForm(forms.ModelForm):
    fight = forms.ModelChoiceField(queryset=Fight.objects.none(), required=False)
    fight_result = forms.ChoiceField(choices=[], required=False)
    method = forms.ChoiceField(
        choices=Prognostic.METHOD_CHOICES,
        widget=AriaLabelRadioSelect(
            attrs={"class": "join-item btn method-field"},
        ),
        required=False,
    )
    bonus = forms.ChoiceField(
        choices=Prognostic.BONUS_CHOICES,
        widget=AriaLabelRadioSelect(
            attrs={"class": "join-item btn bonus-field"},
        ),
        required=False,
    )

    class Meta:
        model = Prognostic
        fields = ["fight_result", "is_draw", "method", "bonus"]

    def __init__(self, *args, **kwargs):
        self.fight = kwargs.pop("fight", None)
        super().__init__(*args, **kwargs)
        if self.fight:
            self.fields["fight_result"].choices = [
                (None, "---------"),
                (self.fight.fighter_one.id, str(self.fight.fighter_one)),
                (self.fight.fighter_two.id, str(self.fight.fighter_two)),
            ]

    def clean_fight_result(self):
        fight_result_id = self.cleaned_data.get("fight_result")
        if fight_result_id and fight_result_id != "None":
            try:
                return Fighter.objects.get(id=fight_result_id)
            except Fighter.DoesNotExist:
                raise forms.ValidationError("Fighter with given ID does not exist")
        return None

    def get_fighter_details(self, fighter: Fighter):
        country_flag_dict = (
            {"country_flag": fighter.country.flag_url} if fighter.country else {}
        )
        return {
            "id": fighter.id,
            "name": fighter.first_name + " " + fighter.last_name,
            "full_name": fighter.full_name(),
            "photo_url": fighter.photo_url,
            "record": fighter.record(),
            **country_flag_dict,
        }

    @property
    def fighter_one_details(self):
        return self.get_fighter_details(self.fight.fighter_one)

    @property
    def fighter_two_details(self):
        return self.get_fighter_details(self.fight.fighter_two)

    @property
    def fight_id(self):
        return self.fight.id if self.fight else None

    @property
    def fight_info(self):
        out = str(self.fight) + ": " + self.fight.weight_class + " "
        out += "Title Fight" if self.fight.belt else "Bout"
        return out

    @property
    def fight_position(self):
        if self.fight.position == 1:
            out = "Main Event"
        elif self.fight.position == 2:
            out = "Co-Main Event"
        elif self.fight.position in range(3, 6):
            out = "Main Card"
        else:
            out = "Prelim"
        return out

    @property
    def fight_card_position(self):
        if self.fight.position == 1:
            out = "main-event"
        elif self.fight.position == 2:
            out = "co-main-event"
        elif self.fight.position in range(3, 6):
            out = "main-card"
        else:
            out = "prelim"
        return out

    @property
    def is_title_fight(self):
        return self.fight.belt


PrognosticFormSet = formset_factory(PrognosticForm, extra=1)

redegg/templates/annual_leaderboard.html
{% extends "base.html" %}
{% block title %}
{{ year }} Leaderboard - Redegg
{% endblock %}
{% block content %}
<h1 class="mb-4 text-2xl font-bold">{{ year }} Leaderboard</h1>
<table class="table table-lg">
  <thead>
    <tr>
      <th>Rank</th>
      <th>User</th>
      <th>Total Score</th>
    </tr>
  </thead>
  <tbody>
    {% for user_id, rank, display_username, score, avatar_url in leaderboard %}
    <tr class="{% if user_id == user.id %}bg-accent{% else %}hover{% endif %}">
      <td>
        {% if rank == 1 %}<i class="fas fa-solid fa-medal" style="color: #ffd700;"></i>
        {% elif rank == 2 %}<i class="fas fa-solid fa-medal" style="color: #c0c0c0;"></i>
        {% elif rank == 3 %}<i class="fas fa-solid fa-medal" style="color: #cd7f32;"></i>
        {% endif %}
        {{ rank }}
      </td>
      {% if user_id == user.id %}
      <td>{% include 'elements/user.html' with username=display_username avatar_url=avatar_url you=True %}</td>
      {% else %}
      <td>{% include 'elements/user.html' with username=display_username avatar_url=avatar_url %}</td>
      {% endif %}
      <td>{{ score }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="3">No predictions yet for this year.</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="pagination">
<span class="step-links">
  {% if page_obj.has_previous %}
  <a href="?page=1">&laquo; first</a>
  <a href="?page={{ page_obj.previous_page_number }}">previous</a>
  {% endif %}

  <span class="current">
  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
  </span>

  {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}">next</a>
  <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
  {% endif %}
</span>
</div>
{% endblock %}

redegg/templates/view_prediction.html
{% extends "base.html" %}
{% block title %}
Redegg - {{ contest_name }}
{% endblock %}
{% block content %}
{% load static %}
<div class="contest-header">
  <div class="contest-title flex justify-between items-center text-center">
    <h1 class="mb-4 text-2xl font-bold">{{ contest_name }}</h1>
    <a class="underline" href="{% url 'contest_leaderboard' contest.slug %}">View Leaderboard</a>
  </div>
  <h2 class="mb-6 italic">{{ contest_date }}</h2>
</div>
{% if user.is_authenticated %}
<div class="score-display mb-2 flex items-center">
    <h3 class="text-lg mx-auto">Points: {{ prediction.points }}</h3>
    <h3 class="text-lg mx-auto">Bonus Modifier: {{ prediction.bonus_modifier }}%</h3>
    <h3 class="text-xl font-bold mx-auto rounded p-1 border-2">Total score: {{ prediction.score }}</h3>
</div>
{% else %}
<p class="italic text-error">You need to be logged in to make prognostics</p>
{% endif %}
<!-- Display the fights and the user's predictions without allowing any input -->
{% for fight, prognostic in fight_prognostic_pairs %}
    <div class="fight-title flex justify-between items-center">
        <h3 class="text-xl my-2 font-bold">{{ fight.fight_info }}
            {% if fight.belt %}
            <img
                src="{% static 'images/belt.jpg' %}"
                alt="Belt"
                class="inline-block h-16 w-auto"
            />
            {% elif fight.bonus %}
            <img
                src=""
                class="inline-block h-16 w-auto"
            />
            {% endif %}
            {% if fight.bonus %}
            <p class="text-lg">
                <i class="fas fa-solid fa-star" style="color: #dbde4f;"></i> {{ fight.get_bonus_display }}
            </p>
            {% endif %}
        </h3>
        <h4 class="text-lg">{{ fight.fight_position }}</h4>
    </div>
        <div class="fight-container" id="fight-{{ fight.id }}" data-fight-position="{{ fight.position }}"> <!-- Add this container -->
            <div class="flex items-center text-center justify-between my-2 fight-result h-44">
                <!-- Display details for each fighter -->
                <div class="h-full w-full selectable selectable-fight-result fighter rounded-md py-2 px-4 m-4 flex-2 flex flex-col items-center justify-center {% if prognostic.fight_result == fight.fighter_one and prognostic.fight_result_won %}prognostic-won {% elif prognostic.fight_result == fight.fighter_one %} prognostic-lost{% endif %}">
                  <div class="flex items-center justify-center">
                    <img class="h-16 object-cover rounded-full mx-auto" src="{{ fight.fighter_one.photo_url }}" alt="{{ fight.fighter_one.name }}" style="pointer-events: none;">
                    <img class="w-6 object-cover" src="{{ fight.fighter_one.country.flag_url }}" onerror="this.style.display='none'">
                  </div>
                  <p>{{ fight.fighter_one.full_name }}</p>
                  <p class="font-semibold {% if fight.wl_fighter_one == 'W' %}text-primary{% elif fight.wl_fighter_one == 'L'%}text-secondary{% endif %}">
                      {{ fight.wl_fighter_one|default:"" }}</br>
                      {% if fight.wl_fighter_one == "W"%}by {{ fight.get_method_display }}{% endif %}
                  </p>
                </div>
                <!-- Draw Checkbox -->
                <div class="h-full w-full selectable selectable-fight-result draw-option rounded-md px-4 m-4 flex-1 flex items-center justify-center {% if fight.is_draw_or_no_contest and prognostic.is_draw %}prognostic-won {% elif prognostic.is_draw %}prognostic-lost {% endif %}">
                    <p>DRAW / NC</p>
                </div>
                <div class="h-full w-full selectable selectable-fight-result fighter rounded-md px-4 m-4 flex-2 flex flex-col items-center justify-center {% if prognostic.fight_result == fight.fighter_two and prognostic.fight_result_won %}prognostic-won {% elif prognostic.fight_result == fight.fighter_two %} prognostic-lost{% endif %}">
                  <div class="flex items-center justify-center">
                    <img class="h-16 object-cover rounded-full mx-auto" src="{{ fight.fighter_two.photo_url }}" alt="{{ fight.fighter_two.name }}" style="pointer-events: none;">
                    <img class="w-6 object-cover" src="{{ fight.fighter_two.country.flag_url }}" onerror="this.style.display='none'">
                  </div>
                  <p>{{ fight.fighter_two.full_name }}</p>
                  <p class="font-semibold {% if fight.wl_fighter_two == 'W' %}text-primary{% elif fight.wl_fighter_two == 'L'%}text-secondary{% endif %}">
                      {{ fight.wl_fighter_two|default:"" }}</br>
                      {% if fight.wl_fighter_two == "W"%}by {{ fight.get_method_display }}{% endif %}
                  </p>
                </div>
                <p class="mr-1">{{ prognostic.points}}</p>    
                {% if fight.fight_result and prognostic.fight_result == fight.fight_result or fight.is_draw_or_no_contest and prognostic.is_draw %}
                <i class="fas fa-check text-green-500"></i>  <!-- Green check mark -->
                {% elif prognostic.fight_result or prognostic.is_draw %}
                    <i class="fas fa-times text-red-500"></i>  <!-- Red cross -->
                {% endif %}
            </div>
            <div class="flex justify-between items-center method-result">
                <div class="join my-2 method-selector">
                    <input class="join-item btn disabled:text-black {% if not prognostic.method_won and prognostic.method == 'decision' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="method-{{ fight.id }}" aria-label="Decision" disabled {% if prognostic.method_won and prognostic.method == "decision" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.method_won and prognostic.method == 'ko_tko' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="method-{{ fight.id }}" aria-label="KO/TKO" disabled {% if prognostic.method_won and prognostic.method == "ko_tko" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.method_won and prognostic.method == 'submission' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="method-{{ fight.id }}" aria-label="Submission" disabled {% if prognostic.method_won and prognostic.method == "submission" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.method_won and prognostic.method == 'cnc' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="method-{{ fight.id }}" aria-label="CNC (Could not continue)" disabled {% if prognostic.method_won and prognostic.method == "cnc" %}checked{% endif %}/>
                </div>
                <p>{% if prognostic.method_won %}30%{% elif prognostic.method %}-30%{% endif %}</p>
            </div>
            <div class="flex justify-between items-center bonus-result">
                <div class="join my-2 bonus-selector">
                    <input class="join-item btn disabled:text-black {% if not prognostic.bonus_won and prognostic.bonus == 'fight' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="bonus-{{ fight.id }}" aria-label="Fight of the Night" disabled {% if prognostic.bonus_won and prognostic.bonus == "fight" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.bonus_won and prognostic.bonus == 'perf' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="bonus-{{ fight.id }}" aria-label="Performance of the Night" disabled {% if prognostic.bonus_won and prognostic.bonus == "perf" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.bonus_won and prognostic.bonus == 'ko' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="bonus-{{ fight.id }}" aria-label="KO of the Night" disabled {% if prognostic.bonus_won and prognostic.method == "ko" %}checked{% endif %}/>
                    <input class="join-item btn disabled:text-black {% if not prognostic.bonus_won and prognostic.bonus == 'sub' %}disabled:bg-red-300{% else %}disabled:bg-gray-200{% endif %}" type="radio" name="bonus-{{ fight.id }}" aria-label="Submission of the Night" disabled {% if prognostic.bonus_won and prognostic.bonus == "sub" %}checked{% endif %}/>
                </div>
                <p>{% if prognostic.bonus_won %}50%{% elif prognostic.bonus %}-50%{% endif %}</p>
            </div>
        </div>
    <div class="divider"></div>
{% endfor %}
{% endblock %}

{% block css %}
<style>
    .prognostic-won.selectable-fight-result {
        border: 2px solid oklch(var(--p));
    }
    .prognostic-lost.selectable-fight-result {
        border: 2px solid oklch(var(--s));
    }
</style>
{% endblock %}